### ISSUE TITLE
Not able to run application in chrome browser through index.html page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#1693]
Reported by Subramanya at https://mifosforge.jira.com/browse/MIFOSX-1919

Not able to run the application in chrome browser through index.html page, Please refer the attached screen shot.

![scr-594](https://cloud.githubusercontent.com/assets/23022667/21088468/44b2b366-c055-11e6-9222-89ae78e0bb68.png)

**Comment by shr33narayan** [comment]
@santoshmath 
This happens due to the **reason** that:
Google Chrome by default does not allow javascript to interact with local file systems. The app is using `global-translations/*.json` files, which is by default not allowed to be displayed since we are directly running it and our url starts with `file:///` or 'C:/` or something similar. Chrome requires 'http://` to make this work smoothly due to their CORS policy.

**Solutions**
There are various solutions to make it working in Chrome.
1. Install http-server or [light-server](https://www.npmjs.com/package/light-server) and run it from there. As simple as `npm i -g light-server` and `light-server app -p 3000`, and open `http://localhost:3000` in Chrome.

2. Before running Chrome use `--allow-file-access-from-file` flag.

This problem will only appear at the app of the chrome unless we run it under node in production. Hence, it doesn't cause any issue impact on production too.

**Comment by gkrishnan724** [comment]
@santoshmath  I don't think this is an issue which we should be concerned about since the app should be run by `grunt serve` it is also not a good practice to test applications by directly opening the HTML page.

**Comment by santoshmath** [comment]
@gkrishnan724 , That is correct. I faced in one of the scenarios , i am not able to run grunt serve and i had to  open index.html through browser. With Mozilla firefox it's working. Same  is expected for chrome.

**Comment by edcable** [comment]
Closing as invalid.
