### ISSUE TITLE
While creating the datatable allowed length for number field is not sufficient

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#1695]
Reported by Subramanya at https://mifosforge.jira.com/browse/MIFOSX-1998
Original Description:
In Admin -> System ->Manage datatables Create datatable for a client with column type number.
Create client and click on the datatable created for the client -> Click on add button -> Enter the 16 digit number in the number field.
> Displayed error meesage as "Error" and not able to submit.

![scr-655](https://cloud.githubusercontent.com/assets/23022667/21127530/9e73c650-c119-11e6-9884-c5e309e1f9af.png)
![scr-656](https://cloud.githubusercontent.com/assets/23022667/21127531/9e75ac7c-c119-11e6-94be-8a4b619045c8.png)

**Comment by ShruthiRajaram** [comment]
@santoshconflux can you help me in understanding this issue? . Number is stored as INT type  with length 11.  And also it can take up-to value -2147483648. So definitely 16 digit can not be stored in INT for a number. Why can't we use String instead of number in such cases or give one more data type of BigDecmal type?

**Comment by santoshconflux** [comment]
@ShruthiRajaram , In  recent version it's showing ""` invalid integer."  which is correct. Closing this ticket.
