### ISSUE TITLE
Align Tree View & Add Account Button at same level as Chart of Accounts title

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1756]
See

https://demo.openmf.org/reskin/#/accounting_coa

<img width="1243" alt="screen shot 2016-12-27 at 8 50 18 am" src="https://cloud.githubusercontent.com/assets/823454/21504190/8bf466b2-cc11-11e6-8eee-ba4cfe601f13.png">

vs

<img width="1240" alt="screen shot 2016-12-27 at 8 50 24 am" src="https://cloud.githubusercontent.com/assets/823454/21504195/913c39a6-cc11-11e6-8b54-718a0a810f64.png">

**Comment by edcable** [comment]
@gkrishnan724 So you thinking have the space is better? @mbj36 @pranjal-goswami @kamdjouduplex what are your thoughts?

**Comment by mbj36** [comment]
Space doesn't makes sense, +1 for the old view

**Comment by pranjal-goswami** [comment]
Hi guys, 
My two cents here :
More than the aesthetic effect that someone might perceive, it is important to have a design consistency in a product - so that a user, after a while, knows "_where will I get the action buttons for the entity on this page?_"

To me, it seems better to keep it at the same level -like @edcable suggested - as the title for two reasons :
1. They are actions on "Chart of Accounts"
2. They save some amount of real estate.

But again, we will have to see that there is consistency in the UI. We should see what is the convention followed in other pages. No matter which one we choose - it should be consistent across the product.

**Comment by edcable** [comment]
I agree with Pranjal's take and am all for consistency. Historically in the old skin it was all at the level of the title so I would continue to follow that same pattern as it saves space as Pranjal said and are actions related to that title.

**Comment by mbj36** [comment]
Perfect. I will send PR for it

**Comment by mbj36** [comment]
Fixed
