### ISSUE TITLE
Reskin:In Edit Financial Activity Mapping page, drop-down menu does not populate GL Accounts

### ISSUE THREAD

**Issue by Ippezrobert** [openMF/community-app#1952]
Create a Financial Activity.
Click on the created Financial Activity to view
Click on Edit Button.

drop-down menu does not populate GL Accounts

**Comment by edcable** [comment]
This should be fixed on the reskin branch of the community app and is high priority.

**Comment by botraunak** [comment]
I cannot find from where do I create a financial activity in the navigation if you can help me that'd be great!  @edcable @Ippezrobert

**Comment by skprabhanjan** [comment]
I got to know  what is wrong here, but need some light on few things so that the fix would be correct. Can anyone tell me what to display in the second dropdown at the starting when "Fund Source" is selected by default in first drop down.?

And The response contains these five things
- assestAccountOptions
- equityAccountOptions
- expenseAccountOptions
- incomeAccountOptions
- liabilityAccountOptions

I can display anyone of this in the second drop down "account"
@mbj36 , @edcable and @Ippezrobert can you please help me on this.?
Thanks:)

**Comment by skprabhanjan** [comment]
@mbj36 , @edcable , @Ippezrobert I understood what was wrong and I have shown the GL account options  in the second dropdown to be "assestAccountOptions" for the activities that have 100,101,102 and 103 as activityID.
So now the drop-down menu for GL account populates on start and works based on activityID according to  the above explanation.
On the above understanding I have created a PR #1974 , Please review it and let me know if there needs to be any changes.
Thanks:)

**Comment by skprabhanjan** [comment]
@mbj36 @santoshmath , Fixed this issue.
Sent a PR #2147 , Please review.
Thanks:)

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
@Ippezrobert , I tested it on new_reskin branch. This issue is fixed.
