### ISSUE TITLE
Entity datatable checks page broken in reskin

### ISSUE THREAD

**Issue by gkrishnan724** [openMF/community-app#1975]
look at : https://demo.openmf.org/newbeta/#/entitydatatablechecks
![screenshot from 2017-03-03 20-34-51](https://cloud.githubusercontent.com/assets/21004514/23556035/0e253ada-0051-11e7-8edb-12f157e20d70.png)

I have done the fix, sending the PR soon :)

**Comment by mbj36** [comment]
Thanks @gkrishnan724

**Comment by santoshmath** [comment]
@mbj36 , Are you sure this issue is totally resolved? I just tested this locally in my machine with latest code. When I click on 'Create entity-data table check' , I am getting this screen:

![entity](https://cloud.githubusercontent.com/assets/23022667/23605837/42f1c67c-0284-11e7-8812-a906f7da7dc1.png)

**Comment by mbj36** [comment]
Thanks. I wasn't aware about this

**Comment by santoshmath** [comment]
@mbj36 , as this issue is something with different scenario, so I rised it as separate issue here:
https://github.com/openMF/community-app/issues/2008
