### ISSUE TITLE
 Dashboard is not showing the charts

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2041]
Screenshot from reskin(https://demo.openmf.org/newbeta/#/richdashboard):

![reskin](https://cloud.githubusercontent.com/assets/23022667/23647824/e1fb4748-033d-11e7-9021-49ab8579ceaa.png)

Screenshot without reskin(https://demo.openmf.org/#/richdashboard)

![demo](https://cloud.githubusercontent.com/assets/23022667/23647839/f8fc1e68-033d-11e7-89ef-d790680921d3.png)

**Comment by DanCarl857** [comment]
Let me attempt this

**Comment by DanCarl857** [comment]
@santoshmath the problem is the libraries used in displaying the charts. The latest version has a know issue with displaying pie charts. This can be found here: [know issue](https://github.com/angularjs-nvd3-directives/angularjs-nvd3-directives/issues/338)

So I reverted those particular directives to an older version and got them to draw the chart. I also fixed the texts in the panel headers. Could you review?

![screen shot 2017-03-08 at 12 45 40 pm](https://cloud.githubusercontent.com/assets/9010142/23702886/8a005a18-03fd-11e7-994e-c6cae8b07ebc.png)

**Comment by santoshmath** [comment]
@mbj36 , Did you check the @DanCarl857 PR?

**Comment by mbj36** [comment]
I don't see any PR opened here

**Comment by DanCarl857** [comment]
So should I redo what I did? Because no one got back to me on downgrading the charting libraries @santoshmath @mbj36

**Comment by DanCarl857** [comment]
@mbj36 this is what I sent: https://github.com/openMF/community-app/pull/2070 and you said you had to discuss with Guarav on it

**Comment by abhaychawla** [comment]
@mbj36 @gkrishnan724 Can I take up this issue?

**Comment by mbj36** [comment]
Yes @abhaychawla

**Comment by abhaychawla** [comment]
Okay!
