### ISSUE TITLE
Reskin: 'Submit' button  is not working on Upload Client Document Page

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2133]
Go to any  Client's page and click on 'Documents' tab. On next page, give the name and path of the file and then click on 'Submit' button. Submit button is not working. 

![reskin](https://cloud.githubusercontent.com/assets/23022667/24233371/d22ed68c-0fb7-11e7-934b-764cf6908b8b.png)

**Comment by syylabs** [comment]
I am working on this. Will send the PR soon.

**Comment by syylabs** [comment]
This is coming when using the 	
http://localhost:9002/?baseApiUrl=https://demo.openmf.org from grunt serve. 

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://demo.openmf.org/fineract-provider/api/v1/clients/6/documents. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

It works fine when using the "https://demo.openmf.org".

To get rid of this the know solution is to have the .htaccess file in the root or redirect to the "https://demo.openmf.org".

**Comment by mbj36** [comment]
@syylabs This issue exists in new_reskin branch. checkout new_reskin branch and let me know if you have any problem

**Comment by syylabs** [comment]
@mbj36 I checked out new_reskin branch. 
I tried to build it with "grunt build" but it is giving "Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined" and fail at running compass dist with following exception. 

"Running "compass:dist" (compass) task
Warning: not found: compass Use --force to continue."

Then I tried with grunt serve. The reported isuue is there when we are using "http://localhost:9002/?baseApiUrl=https://demo.openmf.org#/" type url. But if we use "https://demo.openmf.org#" directly, then the issue is not there. Same with https://github.com/openMF/community-app/issues/2130. ]

**Comment by mbj36** [comment]
Can you make a new fork, then clone and run it again ? 

Checkout new_reskin and do bower install followed with npm install then grunt serve

**Comment by ThisuraThejith** [comment]
@mbj36 Sorry about the confusion first of all. My brother has used my laptop and the account was changed. I just noticed that and removed the comments. Will add those comments below. Really sorry about that.

**Comment by ThisuraThejith** [comment]
This is coming when using the
http://localhost:9002/?baseApiUrl=https://demo.openmf.org from grunt serve.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://demo.openmf.org/fineract-provider/api/v1/clients/6/documents. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

It works fine when using the "https://demo.openmf.org".

To get rid of this the know solution is to have the .htaccess file in the root or redirect to the "https://demo.openmf.org". What should we do?

**Comment by ThisuraThejith** [comment]
@mbj36 I checked out new_reskin branch.
I tried to build it with "grunt build" but it is giving "Loading "grunt-karma.js" tasks...ERROR

TypeError: Cannot read property 'prototype' of undefined" and fail at running compass dist with following exception.
"Running "compass:dist" (compass) task
Warning: not found: compass Use --force to continue."

Then I tried with grunt serve. The reported isuue is there when we are using "http://localhost:9002/?baseApiUrl=https://demo.openmf.org#/" type url. But if we use "https://demo.openmf.org#" directly, then the issue is not there. Same with #2130. ]

**Comment by ThisuraThejith** [comment]
Working on this. Will send the PR soon.

**Comment by dart-wakar** [comment]
@mbj36 This seems like a server side issue...I checked it out and the post request returns a 500 internal server error(java.lang.NullPointerException)

**Comment by ThisuraThejith** [comment]
No the problem is in getting file. The scope.file is null. Working on that and checking for other bugs like this.

**Comment by ThisuraThejith** [comment]
PR sent at https://github.com/openMF/community-app/pull/2148

**Comment by ThisuraThejith** [comment]
@mbj36 Kindly let me know whether the approach in #2148 is correct

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it  on 5/6/2017  on new_reskin branch. This issue is fixed.
