### ISSUE TITLE
Reskin&oldSkin:Unassign staff/officer in saving aplication

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2159]
Create the saving application to a client, assign staff/officer
in saving application level
it is not possible to unassign that staff/officer,,

**Comment by santoshmath** [comment]
This issue exists in old skin and also in reskin.

**Comment by gkrishnan724** [comment]
@santoshmath @Agnessy do you mean the option for unassign staff is missing in the saving account page? I seem to find the unassign button:
![unassign](https://cloud.githubusercontent.com/assets/21004514/24755566/66d03ae2-1af8-11e7-94c6-ce9e33e84f03.png)

Could you please provide a screenshot so that I can understand the problem?

**Comment by santoshmath** [comment]
@gkrishnan724  button is there, but  not working

**Comment by gkrishnan724** [comment]
Ok I'll try and work on this

**Comment by Mastermaulik** [comment]
@gkrishnan724 Please look into this issue

**Comment by gkrishnan724** [comment]
PR #2274 sent

**Comment by mbj36** [comment]
@santoshmath retest and close it

**Comment by santoshmath** [comment]
Tested it on new_reskin branch. This issue is fixed.
