### ISSUE TITLE
Nothing Happens on clicking approve in 'view checker inbox' for updating datatable entry

### ISSUE THREAD

**Issue by skprabhanjan** [openMF/community-app#2182]
Approve in 'view checker inbox' for updation of datatable is not working, on clicking 'approve', loading gif comes and then comes back without anything happening.
Here is an example - https://demo.openmf.org#/viewcheckerinbox/14130
@MexinaD and @santoshmath , Could you please clarify on this.?
Here is the screenshot of that page.
![screen shot 2017-04-27 at 12 25 35 pm](https://cloud.githubusercontent.com/assets/17094832/25471540/337b553e-2b45-11e7-8c0b-b0c5db23f94e.png)

**Comment by SupreethSudhakaranMenon** [comment]
I found this , when i was going across this issue , when i checked this issue in the demo version of the app a pop-up appeared which had two options giving to the user "cancel" and "confirm". I think the issue was fixed and its working fine properly now.
![#2182](https://user-images.githubusercontent.com/45706852/54471528-5b35a700-47e0-11e9-8193-18563ff145ce.png)

**Comment by abhaychawla** [comment]
@santoshconflux I see that the popup is showing in the demo server. Is this issue still present?

**Comment by santoshconflux** [comment]
Yes. This issue no longer exists. Closing it.
