### ISSUE TITLE
Reskin&oldSkin:"Submitted on" is not treated as a mandatory field,when editing the client

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2304]
Create client and then edit that client,
if "submitter on" and "Activation date" fields are not filled , only the activation date error is thrown, and the form can be submitted without inserting "submitted on"(mandatory) .
and after submitted the form capture the previous submitted date
![submitted](https://user-images.githubusercontent.com/13551795/27078696-579fc7ca-503d-11e7-8d5e-0042ba5617a7.png)
.can any one please look at it and let me know if I am wrong somewhere.

**Comment by gkrishnan724** [comment]
Hi @Agnessy, in the latest code of the new skin, `submitted on` field does not seem to be mandatory there is no `*` beside the label please see the screenshot:
![submitted](https://user-images.githubusercontent.com/21004514/27254674-073c81c6-53ab-11e7-9685-f0ba566063de.png)

Hence, I guess you don't have any error when creating the client without filling the field. Since it must be implemented in the server that way. I believe this is not an issue @santoshmath

**Comment by gkrishnan724** [comment]
@Agnessy @santoshmath I believe the submitted on field is not mandatory. Since there is no `*` beside it in the create client area:
![submitted](https://user-images.githubusercontent.com/21004514/27254695-9a48583c-53ab-11e7-93b0-54d1a40c880b.png)
Hence, there is no error when submitting the form in edit client.

I guess we just have to remove the `*` in the edit client view this should solve the confusion

**Comment by santoshmath** [comment]
@gkrishnan724 , good catch. 'Submitted on' date takes by default, yet it's not mandatory. @MexinaD, I tested it old and reskin and found that 'Submitted on' date is not mandatory. Please confirm so that I can close this issue.

**Comment by santoshmath** [comment]
@Mastermaulik , FYI.

**Comment by mbj36** [comment]
Fixed
