### ISSUE TITLE
Unable to submit share product

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#2567]
Provide all mandatory fields but don't provide minimum and maximum 'Shares per client'. 

Unable to submit loan product, not throwing any validation and even response is  not getting generated.

**Comment by mbj36** [comment]
It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

**Sit tight!**

**Comment by ankit01ojha** [comment]
@santoshmath , Should the default value be given in the ```shares per client```. If yes, then the form got submitted, here is the screenshot of the share product form-
![screenshot at 2017-12-09 19 38 32](https://user-images.githubusercontent.com/21126132/33796427-f17606b6-dd19-11e7-8923-f35ea03ad5a9.png)

And, when I don't give any of the fields in the ```shares per client``` (including the default value)  I am getting an error.
![screenshot at 2017-12-09 19 50 38](https://user-images.githubusercontent.com/21126132/33796442-5a991322-dd1a-11e7-9096-21fdb91c7702.png)

**Comment by santoshconflux** [comment]
Invalid.
