### ISSUE TITLE
Searching for groups while creating center is displaying groups which are already member of other center

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#2601]
Go to centers and create a center. While creating center search  for existing groups and select the  group which  is already part of other center. 

> The application is allowing to add the  member group of one center  to new center.

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mdew192837.

**Comment by ankit01ojha** [comment]
I am working on this.

**Comment by gkrishnan724** [comment]
@santoshmath Please create a fineract side issue for the same, since the platform allows adding groups with existing centers. This issue should be resolved in the front-end for now ( the dropdown won't display groups with existing centers), however if somehow the user manages to modify it, then there should be a platform-side validation as well.

**Comment by santoshmath** [comment]
@gkrishnan724 , done:

https://issues.apache.org/jira/browse/FINERACT-589
