### ISSUE TITLE
Access to app without login

### ISSUE THREAD

**Issue by anoited007** [openMF/community-app#2642]
It seems someone can get access to the app interface without login if the person disables some style sheet when using Mozilla. I am sure about other browsers though. Although the user won't be able to manipulate the system, it still poses a risk. You can check the attached screenshots for context. 

![login-bug](https://user-images.githubusercontent.com/27229090/33756155-98a3f4a6-dc0d-11e7-912c-7f3293ccc49e.png)
![login-bug01](https://user-images.githubusercontent.com/27229090/33756156-98e3a4de-dc0d-11e7-8d5a-de68e84712ed.png)

**Comment by mbj36** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @santoshmath, and @Agnessy.

**Comment by gkrishnan724** [comment]
@anoited007 It is never possible to access the data without successful authentication in the API, all data are stored in the API and in order to retrieve any data, successful authentication has to be done. 

I believe we can only have a security risk if any data is being manipulated or being viewed. In this case, none of it is happening. 

Also, Interface of any webpage could be accessed since HTML, CSS and JavaScript is always accessible via the browser. 

I'm not able to understand the security risk in this case.

**Comment by mbj36** [comment]
CC - @nazeer1100126 @avikganguly01

**Comment by anoited007** [comment]
@gkrishnan724 I understand that. My concern was not about accessing the data through this means though. Your clarification about storing the data in the API is helpful.

 However, on the issue of accessing any webpage through such means, I am not really aware of that. Still going through the Mifos X project so I guess I might have some gaps. But from my understanding, the HTML, CSS and JavaScript present on the page affects what is displayed on that page so disabling some shouldn't take me to the page I guess. For example, accessing the loans page directly without auth won't show you the page but rather redirect you to the login page. 

I think it will help if you could clarify this behaviour.

**Comment by gkrishnan724** [comment]
@anoited007  Yes, It will redirect you to the login page. The reason you are able to see the interface is that the login page itself is not a route or a different template, It is just something which covers up the original template which is inside.

You can always access the loan page directly without having the permissions. This is not a security concern since the user won't be seeing the loan-data. He/She would be only be seeing the template of the page. Even in your screenshot, you are just seeing HTML templates with the styles. all the variables are in expresssions `{{ }}` and there is no way to get the data of the variables if you can't log in.

For Eg: I created a user who doesnt have the permissions to see the user list or create user but I can still access the form just by modifying the route to `/createuser` or `/users` but even after modifying the route. All I see is the template form. The list of users will be empty, the dropdown values are empty. No data present. It's just static content. You could easily access it by tweaking the site a little bit. But there is no security concern in accessing static content since they dont have data at all.

Even If I somehow manage to restrict even the access of templates ( This has to be done in JavaScript since the templates are HTML ). The user could easily see the template by just removing the part of the code which restricts it. Although access to data still requires authentication.

Screenshot for createuser form without having permission:
![security](https://user-images.githubusercontent.com/21004514/33765407-af702264-dc3e-11e7-9224-51d85fcc046b.png)

**Comment by edcable** [comment]
Closing this as invalid.
