### ISSUE TITLE
Adding  'Specific Due Date' charge to the loan account when date is not given, is not throwing any validation

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#2658]
1. Create a loan  Account for a client.
2.  Create a specific due date charge.
3. In Loan account, click on 'Add charge' and select specific due date charge, but don't give date and try to submit it.

'Due date is mandatory field but application is accepting null value for it'

Check the screenshot:

![duedate](https://user-images.githubusercontent.com/23022667/33975386-30104060-e0b4-11e7-805f-d9fa63f39850.png)

**Comment by Agnessy** [comment]
Hi @santoshmath , 
I updated my code, i see it works fine..
see a screen-shot..
![adding](https://user-images.githubusercontent.com/13551795/34105583-f0a48878-e405-11e7-8981-5cbb3775e70c.png)
Or ,,  Can you take a look? and correct me

**Comment by abhaychawla** [comment]
@santoshconflux @ShruthiRajaram @gkrishnan724 I think the issue is no longer reproducible. I tested on the demo server and got a validation error. Can you please check and close this? This is also present as a GCI task and a student tried to attempt it here but was unable to reproduce it as well: https://codein.withgoogle.com/dashboard/task-instances/5266254341341184/

**Comment by gkrishnan724** [comment]
@abhaychawla @santoshmath, I believe the error exists. I tried submitting it for the  same loan account and charge as given in santosh's screenshot i.e : `https://staging.openmf.org/#/addloancharge/50 ` and select the charge as `sew` when you hit submit without  giving the date. It gives an internal server error.

This is the response if you see it in the network tab: `{"timestamp":1544418611664,"status":500,"error":"Internal Server Error","exception":"java.lang.NullPointerException","message":null}` I believe this is a server side error.

**Comment by ShruthiRajaram** [comment]
Issue is fixed . Closing the issue

**Comment by ShruthiRajaram** [comment]
@gkrishnan724 agreed.
@santoshconflux  it is a null pointer exception, so kindly create an issue in Fineract Jira as well. 

Due date is a mandatory field and it is not handled properly in front end. It is allowing null as well. So @abhaychawla I too believe this should be fixed in community-app. So for this issue, making due-date go through mandatory check(not just the asterisk symbol)  should be added.  Correct me if I am wrong.

**Comment by santoshconflux** [comment]
@ShruthiRajaram , sure

**Comment by abhaychawla** [comment]
Yes, I agree with you. @ShruthiRajaram @gkrishnan724  But I am not sure why when I tried it here I didn't get a null pointer exception just this error:

![screenshot 362](https://user-images.githubusercontent.com/16948598/49746219-bb3f1d80-fcc6-11e8-9364-6cc802f8529d.png)

**Comment by santoshconflux** [comment]
Fineract side ticket: https://issues.apache.org/jira/browse/FINERACT-671
