### ISSUE TITLE
Logo is not getting updating even the logo is changed in logo.json file

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#2934]
In login page  , the logo next to MifosX (check the screenshot) is not getting updated even the logo is changed in logo.json file.

![screenshot from 2018-04-05 11-22-53](https://user-images.githubusercontent.com/23022667/38349236-b96e88b4-38c3-11e8-9621-a4b2e79a8705.png)

**Comment by abiyats** [comment]
Both the text and logo are in the same image.
If you with to change it, you will need to go to our tomcat --> ROOT --> images --> /images/mifos-logo-flat.png
Create your own image and rename it like "mifos-logo-flat.png" Delete the old one.
Clear cache of your browser. (Ctrl + Shift + Delete).

Then you will see the effect.

**Comment by santoshconflux** [comment]
Thank you @abiyats

**Comment by ShruthiRajaram** [comment]
@abiyats  and @santoshconflux the logo which is currently displayed is an approved one. I believe the issue is with having client specific logo which was supported in earlier version and in current version this feature is not available. 
@santoshconflux  kindly check with support team. @edcable correct me if I am wrong

**Comment by santoshconflux** [comment]
@ShruthiRajaram , this ticket can be closed.
