### ISSUE TITLE
 Not able to create the client address due to missing street field in UI

### ISSUE THREAD

**Issue by kiran-vsm** [openMF/community-app#3249]
Not able to create the client address due to missing fields in UI

## Settings

- Mifos X version: 
- Browser used:
- OS:

## Screenshots
![image](https://user-images.githubusercontent.com/65952533/116776771-f7d26600-aa87-11eb-98e2-f3f3d8229adc.png)

**Comment by kiran-vsm** [comment]
Pull Request Link : https://github.com/openMF/community-app/pull/3250

**Comment by bharathcgowda** [comment]
this issue is fixed but a new has been raised where no field is being listed when we select to add a client address
![image](https://user-images.githubusercontent.com/65952533/116776758-ea1ce080-aa87-11eb-82d2-0d918652d960.png)

**Comment by bharathcgowda** [comment]
NOTE: support@habile.in . Habile team is currently working on this Issue.

**Comment by bharathcgowda** [comment]
Hi Ramesh/ Charulatha, address addition to the client is working from the client view page, however, it is not working from "create client screen".

State and country dropdown are not getting values, because of which the client creation is not happening, could you please check again

To reproduce.
Create a client, add address while creating client as shown in the screenshot.

![image](https://user-images.githubusercontent.com/65952533/120493362-85cba480-c3d8-11eb-9793-c2a3dc3524f6.png)

**Comment by bharathcgowda** [comment]
@habile-technologies

**Comment by bharathcgowda** [comment]
fixed, thanks to @josehernandezfintecheandomx
